/**
 * Carros de exemplo (lote 5b fase A, `docs/briefings/app-web-lote5.md`):
 * usados só para montar os anúncios do Clube da Troca. Sem `imageFileId`
 * real — os cards caem no fallback (silhueta), como qualquer carro sem foto.
 */

import type { CarItem } from "@/lib/app-types";

export const MOCK_CARS: CarItem[] = [
  {
    id: "mock-car-1",
    title: "Custom Camaro",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-muscle",
    serieTitle: "Muscle Mania",
    seriePosition: "3/10",
    seriePositionNum: 3,
    collector: "017",
    color: "Amarelo",
    toy: "GRY55",
    year: 2024,
    scale: "1:64",
    imageFileId: null,
    attributeIds: [],
  },
  {
    id: "mock-car-2",
    title: "'67 Mustang Fastback",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-muscle",
    serieTitle: "Muscle Mania",
    seriePosition: "5/10",
    seriePositionNum: 5,
    collector: "019",
    color: "Azul metálico",
    toy: "GRY57",
    year: 2024,
    scale: "1:64",
    imageFileId: null,
    attributeIds: ["attr-thunt"],
  },
  {
    id: "mock-car-3",
    title: "Nissan Skyline GT-R (R34)",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-jdm",
    serieTitle: "JDM Legends",
    seriePosition: "2/8",
    seriePositionNum: 2,
    collector: "104",
    color: "Prata",
    toy: "HKC42",
    year: 2023,
    scale: "1:64",
    imageFileId: null,
    attributeIds: [],
  },
  {
    id: "mock-car-4",
    title: "Toyota Supra MK4",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-jdm",
    serieTitle: "JDM Legends",
    seriePosition: "4/8",
    seriePositionNum: 4,
    collector: "106",
    color: "Vermelho",
    toy: "HKC44",
    year: 2023,
    scale: "1:64",
    imageFileId: null,
    attributeIds: [],
  },
  {
    id: "mock-car-5",
    title: "Lamborghini Huracán",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-super",
    serieTitle: "Super Sport",
    seriePosition: "1/5",
    seriePositionNum: 1,
    collector: "201",
    color: "Verde",
    toy: "FYB12",
    year: 2022,
    scale: "1:64",
    imageFileId: null,
    attributeIds: ["attr-sthunt"],
  },
  {
    id: "mock-car-6",
    title: "Porsche 911 GT3 RS",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-super",
    serieTitle: "Super Sport",
    seriePosition: "3/5",
    seriePositionNum: 3,
    collector: "203",
    color: "Branco",
    toy: "FYB14",
    year: 2022,
    scale: "1:64",
    imageFileId: null,
    attributeIds: [],
  },
  {
    id: "mock-car-7",
    title: "'70 Chevelle SS",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-muscle",
    serieTitle: "Muscle Mania",
    seriePosition: "8/10",
    seriePositionNum: 8,
    collector: "022",
    color: "Laranja",
    toy: "GRY60",
    year: 2024,
    scale: "1:64",
    imageFileId: null,
    attributeIds: [],
  },
  {
    id: "mock-car-8",
    title: "Mazda RX-7 FD",
    description: "",
    brandId: "brand-hw",
    brandName: "Hot Wheels",
    serieId: "serie-jdm",
    serieTitle: "JDM Legends",
    seriePosition: "6/8",
    seriePositionNum: 6,
    collector: "108",
    color: "Preto",
    toy: "HKC46",
    year: 2023,
    scale: "1:64",
    imageFileId: null,
    attributeIds: [],
  },
];

export function findMockCar(id: string): CarItem {
  return MOCK_CARS.find((car) => car.id === id) ?? MOCK_CARS[0];
}
